### PR TITLE
Fix login exception

### LINKED ISSUE #35: ProviderException on logout: accountPubkeyProvider accessed before authentication
An exception is thrown when the user logs out on the Settings screen. The `SettingsScreen` attempts to access `accountPubkeyProvider` after authentication state has been cleared, causing a `ProviderException` to be thrown.

https://github.com/user-attachments/assets/c68490d7-4307-4c01-a334-0b197a35dcea

Logs:
cc(40)] Unhandled Exception: Bad state: accountPubkeyProvider accessed without authentication
#0      accountPubkeyProvider.<anonymous closure> (package:sloth/providers/account_pubkey_provider.dart:7:5)
#1      Provider.create (package:riverpod/src/providers/provider.dart:59:36)
#2      $ProviderElement.create (package:riverpod/src/providers/provider.dart:343:32)
#3      ProviderElement.buildState (package:riverpod/src/core/element.dart:674:28)
#4      ProviderElement._performRebuild (package:riverpod/src/core/element.dart:579:7)
#5      ProviderElement.flush (package:riverpod/src/core/element.dart:637:7)
#6      ProviderScheduler._performRefresh (package:riverpod/src/core/scheduler.dart:132:37)
#7      ProviderScheduler._task (package:riverpod/src/core/scheduler.dart:106:5)
#8      Task.call (package:riverpod/src/core/scheduler.dart:14:16)
#9      _UncontrolledProviderScopeState._callTask (package:flutter_riverpod/src/core/provider_scope.dart:292:11)
#10   <…>

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞══════════════════════════════════════════
═════════════════
The following ProviderException was thrown
building SettingsScreen(dirty,
dependencies:
[InheritedCupertinoTheme,
_EffectiveTickerMode, _InheritedTheme,
_LocalizationsScope-[GlobalKey#010a5],
_ModalScopeStatus,
_UncontrolledProviderScope], state:
_ConsumerState#42821):
Tried to use a provider that is in error
state.

A provider threw the following exception:
Bad state: accountPubkeyProvider accessed
without authentication

The stack trace of the exception:
#0      accountPubkeyProvider.<anonymous
closure>
(package:sloth/providers/account_pubkey_pro
vider.dart:7:5)
#1      Provider.create
(package:riverpod/src/providers/provider.da
rt:59:36)
#2      $ProviderElement.create
(package:riverpod/src/providers/provider.da
rt:343:32)
#3      ProviderElement.buildState
(package:riverpod/src/core/element.dart:674
:28)
#4      ProviderElement._performRebuild
(package:riverpod/src/core/element.dart:579
:7)
#5      ProviderElement.flush
(package:riverpod/src/core/element.dart:637
:7)
#6      ProviderScheduler._performRefresh
(package:riverpod/src/core/scheduler.dart:1
32:37)
#7      ProviderScheduler._task
(package:riverpod/src/core/scheduler.dart:1
06:5)
#8      Task.call
(package:riverpod/src/core/scheduler.dart:1
4:16)
#9
_UncontrolledProviderScopeState._callTask
(package:flutter_riverpod/src/core/provider
_scope.dart:292:11)
#10
_UncontrolledProviderScopeState._flutterVsy
nc.<anonymous closure>.<anonymous closure>
(package:flutter_riverpod/src/core/provider
_scope.dart:324:9)
#11     Timer._createTimer.<anonymous
closure>
(dart:async-patch/timer_patch.dart:18:15)
#12     _Timer._runTimers
(dart:isolate-patch/timer_impl.dart:423:19)
#13     _Timer._handleMessage
(dart:isolate-patch/timer_impl.dart:454:5)
#14     _RawReceivePort._handleMessage
(dart:isolate-patch/isolate_patch.dart:193:
12)

The relevant error-causing widget was:
  SettingsScreen
  SettingsScreen:file:///Users/untreu/Docum
  ents/GitHub/sloth/lib/routes.dart:86:26

When the exception was thrown, this was the
stack:
#0      throwProviderException
(package:riverpod/src/common/stack_trace.da
rt:10:3)
#1
$ResultError.valueOrProviderException
(package:riverpod/src/common/result.dart:10
8:7)
#2      ConsumerStatefulElement.watch
(package:flutter_riverpod/src/core/consumer
.dart:459:14)
#3      SettingsScreen.build
(package:sloth/screens/settings_screen.dart
:21:24)
#4      _ConsumerState.build
(package:flutter_riverpod/src/core/consumer
.dart:283:48)
#5      StatefulElement.build
(package:flutter/src/widgets/framework.dart
:5934:27)
#6      ConsumerStatefulElement.build
(package:flutter_riverpod/src/core/consumer
.dart:421:20)
#7      HookElement.build
(package:flutter_hooks/src/framework.dart:4
38:27)
#8      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart
:5820:15)
#9      StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart
:5985:11)
#10     Element.rebuild
(package:flutter/src/widgets/framework.dart
:5532:7)
#11     BuildScope._tryRebuild
(package:flutter/src/widgets/framework.dart
:2750:15)
#12     BuildScope._flushDirtyElements
(package:flutter/src/widgets/framework.dart
:2807:11)
#13     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart
:3111:18)
#14     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:1
262:21)
#15
RendererBinding._handlePersistentFrameCallb
ack
(package:flutter/src/rendering/binding.dart
:495:5)
#16
SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart
:1434:15)
#17     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart
:1347:9)
#18     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart
:1200:5)
#19     _invoke (dart:ui/hooks.dart:356:13)
#20     PlatformDispatcher._drawFrame
(dart:ui/platform_dispatcher.dart:444:5)
#21     _drawFrame
(dart:ui/hooks.dart:328:31)

═══════════════════════════════════════════
═══════════════════════════════════════════
══════════════

### PR DESCRIPTION
**Pull request by erskingardner**
## Description

The design intent between `accountPubkeyProvider` and the `authProvider`:
`accountPubkeyProvider` is a convenience provider for screens that should only be accessed when authenticated. It gives you a non-nullable `String` so you don't have to null-check everywhere. The assumption is that the router redirects unauthenticated users away from protected screens, so the provider should never be accessed when pubkey is null.

The problem we hit:
During logout, there's a brief window where:
1. `authProvider` sets pubkey to null
2. Riverpod triggers rebuilds on widgets watching providers
3. `SettingsScreen` and `SignOutScreen` try to rebuild
4. They watch `accountPubkeyProvider`, which throws

The fix was to watch `authProvider.value` directly and return an empty widget when pubkey is `null`, handling the race condition gracefully.

This also adds a log out confirmation page to make sure users understand the consequences of their actions.

Fixes #35 

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

## Checklist

- [X] Run `just precommit` to ensure that formatting and linting are correct
- [x] Updated the `CHANGELOG.md` file with your changes (if they affect the user experience)

## Summary by CodeRabbit

* **New Features**
  * Dedicated sign-out screen with private-key backup UI and guidance
  * Private-key visibility toggle and unified copy buttons for keys
  * Settings now navigate to the new sign-out flow

* **Bug Fixes**
  * Resolved an exception during sign-out

* **Tests**
  * Added and updated tests covering SignOutScreen, copyable key widget, and nullable-hook scenarios

* **Documentation**
  * Updated contributor checklist and changelog guidance

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by erskingardner** [comment]
@coderabbitai review

File: lib/screens/settings_screen.dart [hunk 1]
```diff
@@ -18,7 +17,11 @@ class SettingsScreen extends HookConsumerWidget {
   @override
   Widget build(BuildContext context, WidgetRef ref) {
     final colors = context.colors;
-    final pubkey = ref.watch(accountPubkeyProvider);
+    final pubkey = ref.watch(authProvider).value;
+
+    if (pubkey == null) {
```
Comment (josefinalliende) [inline lib/screens/settings_screen.dart]: This check shouldn't be necessary now that logout is called in another screen. I think we can just use the `accountPubkeyProvider` here  and only check this in the sign out screen

File: test/screens/sign_out_screen_test.dart [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+      expect(textField, findsOneWidget);
+      final fieldText = tester.widget<TextFormField>(textField).controller?.text ?? '';
+      expect(fieldText, startsWith('nsec1'));
+    });
+
+    testWidgets('tapping copy button copies private key to clipboard', (tester) async {
+      final getClipboard = mockClipboard();
+      await pumpSignOutScreen(tester);
+      await tester.pumpAndSettle();
+      final copyButton = find.byIcon(Icons.copy);
```
Comment (josefinalliende) [inline test/screens/sign_out_screen_test.dart]: This I something I learned later so there are tests with find by icon in the repo, but know we are trying to add keys for icons and in tests find by key. We know that we are going to change icons to svgs in assets soon and when we do if tests are  with find.byIcon, loots of tests will break

File: test/screens/sign_out_screen_test.dart [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+      overrides: [
+        authProvider.overrideWith(() => mockAuth),
+        secureStorageProvider.overrideWithValue(MockSecureStorage()),
+      ],
+    );
+    Routes.pushToSignOut(tester.element(find.byType(Scaffold)));
+    await tester.pumpAndSettle();
+  }
+
+  group('SignOutScreen', () {
```
Comment (josefinalliende) [inline test/screens/sign_out_screen_test.dart]: I think there is a test case missing for the null active pubkey case that generated the issue. it would be nice to add it so that we make sure that is not happening as it did before in the settings screen

File: test/screens/sign_out_screen_test.dart (hunk 2 above)
Comment (erskingardner) [reply test/screens/sign_out_screen_test.dart]: ok - that's ok though right? we just leave this alone for now and we'll fix all that when we're ready with the svgs?
